# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['backend/dev_server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('frontend/dist', 'frontend/dist'),
        ('backend/commands_dev.yaml', 'backend'),
    ],
    hiddenimports=[
        'flask',
        'flask_cors',
        'pandas',
        'plotly',
        'yaml',
        'jsonrpclib',
        'werkzeug',
        'openpyxl',
        'queue',
        'socket',
        'urllib3',
        'ssl',
        'json',
        'threading',
        'concurrent.futures',
        'difflib',
        'logging',
        'time',
        'uuid',
        'datetime',
        'pathlib',
        'typing',
        'dataclasses',
        'tempfile',
        'io',
        'base64',
        'collections',
        'importlib.metadata'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='NetworkDataApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    coerce_archive=True,
    cipher=block_cipher,
)
